trainer:
  max_epochs: 100
  val_check_interval: 0.1
  callbacks:
    class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      monitor: val_iou
      mode: max
data:
  root: KITTISnow
  snow_rate: light
optimizer:
  class_path: torch.optim.SGD
  init_args:
    lr: 0.1
lr_scheduler:
  class_path: torch.optim.lr_scheduler.ExponentialLR
  init_args:
    gamma: 0.9